(()=>{
const V22_TAB_KEY='carteira-v22-tab';
const V22_DIV_UI_KEY='carteira-v22-dividend-ui';
const V22_TABS=['patrimonio','macro','micro','proventos'];
const V22_LABELS={patrimonio:'Patrimônio',macro:'Macro alocação',micro:'Micro alocação',proventos:'Proventos'};
const V22_ICONS={patrimonio:'◫',macro:'◎',micro:'▦',proventos:'◌'};
const V22_COLORS=['#43d39e','#69a7ff','#f2b66d','#b28cff','#5ed1dc','#ff8f9b','#93c86f','#cf9bff','#6fb6a7','#e1cf6a'];
let v22Ready=false;
let v22DividendDb={updatedAt:null,events:[],sources:[]};
let v22DividendLoaded=false;
let v22ActiveTab=(()=>{const h=String(location.hash||'').replace('#','');if(V22_TABS.includes(h))return h;const s=localStorage.getItem(V22_TAB_KEY);return V22_TABS.includes(s)?s:'patrimonio';})();
let v22DividendUi=(()=>{try{const x=JSON.parse(localStorage.getItem(V22_DIV_UI_KEY)||'null');return x&&typeof x==='object'?{mode:x.mode==='annual'?'annual':'monthly',range:['year','12','24','all'].includes(x.range)?x.range:'year',status:['Todos','Recebidos','A receber'].includes(x.status)?x.status:'Todos'}:{mode:'monthly',range:'year',status:'Todos'};}catch(e){return {mode:'monthly',range:'year',status:'Todos'};}})();
function escV22(v){return typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function attrV22(v){return typeof escapeAttr==='function'?escapeAttr(String(v??'')):escV22(v);}
function moneyV22(v){return Number.isFinite(+v)?fmt.format(+v):'—';}
function pctV22(v){return typeof pct==='function'?pct(+v||0):`${(+v||0).toFixed(1).replace('.',',')}%`;}
function tickerV22(v){const t=String(v||'').trim().toUpperCase();return t==='BTC'?'BTCUSD':t;}
function isoDateV22(v){if(!v)return null;const s=String(v).slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null;}
function brDateV22(v){const s=isoDateV22(v);if(!s)return '—';const [y,m,d]=s.split('-');return `${d}/${m}/${y}`;}
function parseDateV22(v){const s=isoDateV22(v);return s?new Date(`${s}T12:00:00`):null;}
function todayV22(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function monthKeyV22(v){const d=v instanceof Date?v:parseDateV22(v);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:null;}
function monthLabelV22(k){const [y,m]=k.split('-');return `${m}/${String(y).slice(-2)}`;}
function fxV22(){try{const f=typeof fxUsdBrlV20==='function'?fxUsdBrlV20():null;return Number.isFinite(+f)?+f:null;}catch(e){return null;}}
function saveDividendUiV22(){localStorage.setItem(V22_DIV_UI_KEY,JSON.stringify(v22DividendUi));}
function updateVersionV22(){const e=document.querySelector('.topbar .eyebrow');if(e)e.textContent='CARTEIRA • V2.2';}
function ensureCssV22(){if(document.querySelector('link[href^="v22.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='v22.css?v=22.0';document.head.appendChild(l);}
function panelV22(id){let p=document.getElementById(id);if(!p){p=document.createElement('section');p.id=id;p.className='tabPanelV22';const footer=document.querySelector('main.shell > footer');(footer?.parentNode||document.querySelector('main.shell')).insertBefore(p,footer||null);}return p;}
function navV22(){let nav=document.getElementById('portfolioTabsV22');if(nav)return nav;nav=document.createElement('nav');nav.id='portfolioTabsV22';nav.className='portfolioTabsV22';nav.setAttribute('aria-label','Seções da carteira');nav.innerHTML=V22_TABS.map(t=>`<button type="button" data-tab-v22="${t}"><span class="tabIconV22">${V22_ICONS[t]}</span><span>${V22_LABELS[t]}</span></button>`).join('');const top=document.querySelector('.topbar');top?.insertAdjacentElement('afterend',nav);nav.querySelectorAll('[data-tab-v22]').forEach(b=>b.onclick=()=>activateTabV22(b.dataset.tabV22,true));return nav;}
function ensurePanelHeadersV22(){const macro=panelV22('tabMacroV22');if(!macro.querySelector('.tabIntroV22'))macro.insertAdjacentHTML('afterbegin','<div class="tabIntroV22"><div><span class="tabEyebrowV22">ALOCAÇÃO E APORTES</span><h2>Macro alocação</h2><p>Planeje pesos por classe, banda de desbalanceamento e distribuição do próximo aporte.</p></div></div>');const micro=panelV22('tabMicroV22');if(!micro.querySelector('.tabIntroV22'))micro.insertAdjacentHTML('afterbegin','<div class="tabIntroV22"><div><span class="tabEyebrowV22">POSIÇÕES E LANÇAMENTOS</span><h2>Micro alocação</h2><p>Gerencie ativos, segmentos, simulações e o histórico de lançamentos.</p></div></div>');const pro=panelV22('tabProventosV22');if(!pro.querySelector('.tabIntroV22'))pro.insertAdjacentHTML('afterbegin','<div class="tabIntroV22"><div><span class="tabEyebrowV22">RENDA DA CARTEIRA</span><h2>Proventos</h2><p>Acompanhe pagamentos recebidos e anunciados somente para posições que fazem parte da sua carteira.</p></div></div>');}
function macroBudgetCardV22(){let card=document.getElementById('macroBudgetCardV22');if(!card){card=document.createElement('section');card.id='macroBudgetCardV22';card.className='card macroBudgetCardV22';card.innerHTML='<div class="sectionTitle"><div><h2>Planejamento de aportes</h2><p>Defina o orçamento do mês. A sugestão automática e a simulação continuam obedecendo à mesma regra de precedência.</p></div></div><div id="macroBudgetHostV22"></div>';const macro=panelV22('tabMacroV22');const intro=macro.querySelector('.tabIntroV22');intro?.insertAdjacentElement('afterend',card);}const controls=document.getElementById('txBudgetControlsV16');if(controls&&controls.parentElement?.id!=='macroBudgetHostV22')document.getElementById('macroBudgetHostV22')?.appendChild(controls);return card;}
function patrimonyOverviewHostsV22(){const p=panelV22('tabPatrimonioV22');let g=document.getElementById('patrimonyOverviewGridV22');if(!g){g=document.createElement('div');g.id='patrimonyOverviewGridV22';g.className='patrimonyOverviewGridV22';g.innerHTML='<section id="patrimonyIncomeSummaryV22" class="card overviewCardV22"></section><section id="patrimonyMicroSummaryV22" class="card overviewCardV22 microSummaryCardV22"></section>';p.appendChild(g);}return g;}
function buildProventosShellV22(){const p=panelV22('tabProventosV22');if(document.getElementById('dividendWorkspaceV22'))return;const wrap=document.createElement('div');wrap.id='dividendWorkspaceV22';wrap.innerHTML=`<section id="dividendKpisV22" class="dividendKpisV22"></section><section class="card dividendChartCardV22"><div class="dividendHeaderV22"><div><h2>Evolução dos proventos</h2><p>Valores brutos estimados a partir da quantidade elegível em cada data-com.</p></div><div class="dividendControlsV22"><div class="segmentedV22"><button id="divModeMonthlyV22" type="button">Mensal</button><button id="divModeAnnualV22" type="button">Anual</button></div><select id="divRangeV22"><option value="year">Ano atual</option><option value="12">12 meses</option><option value="24">24 meses</option><option value="all">Todo histórico</option></select></div></div><div id="dividendChartV22" class="dividendChartV22"></div><div class="dividendLegendV22"><span><i class="received"></i>Recebidos</span><span><i class="upcoming"></i>A receber</span></div><div id="dividendChartFootV22" class="dividendFootV22"></div></section><section class="card dividendListCardV22"><div class="dividendHeaderV22"><div><h2>Lista de proventos</h2><p>Somente ativos com posição atual na carteira. Pagamentos em USD são convertidos para BRL apenas para consolidação visual.</p></div><div class="dividendControlsV22"><select id="divStatusV22"><option>Todos</option><option>Recebidos</option><option>A receber</option></select></div></div><div id="dividendCoverageV22" class="dividendCoverageV22"></div><div class="tableWrap"><table class="dividendTableV22"><thead><tr><th>Ativo</th><th>Classe</th><th>Tipo</th><th>Data-com</th><th>Pagamento</th><th>Valor unitário</th><th>Qtd. elegível</th><th>Total</th><th>Status</th></tr></thead><tbody id="dividendRowsV22"></tbody></table></div></section>`;p.appendChild(wrap);document.getElementById('divModeMonthlyV22').onclick=()=>{v22DividendUi.mode='monthly';saveDividendUiV22();renderDividendsV22();};document.getElementById('divModeAnnualV22').onclick=()=>{v22DividendUi.mode='annual';saveDividendUiV22();renderDividendsV22();};document.getElementById('divRangeV22').onchange=e=>{v22DividendUi.range=e.target.value;saveDividendUiV22();renderDividendsV22();};document.getElementById('divStatusV22').onchange=e=>{v22DividendUi.status=e.target.value;saveDividendUiV22();renderDividendTableV22();};}
function ensureTabLayoutV22(){navV22();panelV22('tabPatrimonioV22');panelV22('tabMacroV22');panelV22('tabMicroV22');panelV22('tabProventosV22');ensurePanelHeadersV22();buildProventosShellV22();const patr=panelV22('tabPatrimonioV22'),macro=panelV22('tabMacroV22'),micro=panelV22('tabMicroV22');const kpis=document.getElementById('kpis'),evo=document.querySelector('.evolutionCard'),charts=document.querySelector('.chartsCard'),layout=document.querySelector('.layout'),tx=document.getElementById('transactionsSection'),hold=document.querySelector('.holdingsCard');if(kpis&&kpis.parentElement!==patr)patr.appendChild(kpis);if(evo&&evo.parentElement!==patr)patr.appendChild(evo);if(charts&&charts.parentElement!==patr)patr.appendChild(charts);patrimonyOverviewHostsV22();macroBudgetCardV22();if(layout&&layout.parentElement!==macro)macro.appendChild(layout);if(tx&&tx.parentElement!==micro)micro.appendChild(tx);if(hold&&hold.parentElement!==micro)micro.appendChild(hold);const chartsTitle=charts?.querySelector('.sectionTitle h2');if(chartsTitle)chartsTitle.innerHTML=`Resumo da macro alocação ${typeof infoV16==='function'?infoV16('Visão resumida da distribuição atual por classe. A definição e o planejamento das metas ficam na aba Macro alocação.') : ''}`;const chartsP=charts?.querySelector('.sectionTitle p');if(chartsP)chartsP.textContent='Composição atual da carteira e comparação opcional com os pesos-alvo.';}
function activateTabV22(tab,pushHash=false){if(!V22_TABS.includes(tab))tab='patrimonio';v22ActiveTab=tab;localStorage.setItem(V22_TAB_KEY,tab);if(pushHash&&location.hash!==`#${tab}`)history.replaceState(null,'',`#${tab}`);document.querySelectorAll('.tabPanelV22').forEach(p=>p.classList.toggle('hiddenV22',p.id!==({patrimonio:'tabPatrimonioV22',macro:'tabMacroV22',micro:'tabMicroV22',proventos:'tabProventosV22'}[tab])));document.querySelectorAll('[data-tab-v22]').forEach(b=>{const a=b.dataset.tabV22===tab;b.classList.toggle('active',a);b.setAttribute('aria-selected',a?'true':'false');});if(tab==='patrimonio'){try{renderPatrimonyEvolutionV15();}catch(e){}renderPatrimonySummariesV22();}if(tab==='proventos')renderDividendsV22();}
function segmentPlanV22(className){try{return typeof ensureSegmentPlanV18==='function'?ensureSegmentPlanV18(className):[];}catch(e){return [];}}
function currentSegmentRowsV22(className){const map=new Map(),items=(state.holdings||[]).filter(h=>h.className===className&&(+h.qty||0)>1e-10);items.forEach(h=>{const n=String(h.segment||'Sem segmento').trim()||'Sem segmento';const key=n.toLocaleLowerCase('pt-BR');if(!map.has(key))map.set(key,{name:n,value:0,target:0});map.get(key).value+=Math.max(0,+h.value||0);});segmentPlanV22(className).forEach(s=>{const n=String(s.name||'').trim();if(!n)return;const key=n.toLocaleLowerCase('pt-BR');if(!map.has(key))map.set(key,{name:n,value:0,target:Math.max(0,+s.target||0)});else map.get(key).target=Math.max(0,+s.target||0);});const total=[...map.values()].reduce((s,r)=>s+r.value,0);return [...map.values()].map(r=>({...r,weight:total?r.value/total*100:0})).sort((a,b)=>b.value-a.value);}
function pieGradientV22(rows){const positive=rows.filter(r=>r.weight>0);if(!positive.length)return 'conic-gradient(#193149 0 100%)';let acc=0;const stops=[];positive.forEach((r,i)=>{const start=acc,end=acc+r.weight,clr=V22_COLORS[i%V22_COLORS.length];stops.push(`${clr} ${start}% ${end}%`);acc=end;});return `conic-gradient(${stops.join(',')})`;}
function renderMicroSummaryV22(){const host=document.getElementById('patrimonyMicroSummaryV22');if(!host)return;const classes=(state.assets||[]).filter(a=>(state.holdings||[]).some(h=>h.className===a.name&&(+h.qty||0)>1e-10));if(!classes.length){host.innerHTML='<div class="overviewHeaderV22"><div><h2>Resumo da micro alocação</h2><p>Nenhuma posição ativa.</p></div></div>';return;}host.innerHTML=`<div class="overviewHeaderV22"><div><h2>Resumo da micro alocação</h2><p>Distribuição setorial atual dentro de cada classe.</p></div><button type="button" class="ghost compact" data-go-micro-v22>Ver micro alocação</button></div><div class="microSummaryGridV22">${classes.map(a=>{const rows=currentSegmentRowsV22(a.name),total=rows.reduce((s,r)=>s+r.value,0),top=rows.slice(0,4);return `<article class="microMiniV22"><header><strong>${escV22(a.name)}</strong><span>${moneyV22(total)}</span></header><div class="microMiniBodyV22"><div class="miniPieV22" style="background:${pieGradientV22(rows)}"><span>${rows.filter(r=>r.weight>0).length}</span></div><div class="microMiniLegendV22">${top.map((r,i)=>`<div><i style="background:${V22_COLORS[i%V22_COLORS.length]}"></i><span>${escV22(r.name)}</span><strong>${pctV22(r.weight)}</strong>${r.target>0?`<small>alvo ${pctV22(r.target)}</small>`:''}</div>`).join('')}${rows.length>4?`<small class="moreV22">+ ${rows.length-4} segmento(s)</small>`:''}</div></div></article>`;}).join('')}</div>`;host.querySelector('[data-go-micro-v22]')?.addEventListener('click',()=>activateTabV22('micro',true));}
function activeHoldingsV22(){return (state.holdings||[]).filter(h=>(+h.qty||0)>1e-10);}
function historyForTickerV22(ticker){const key=tickerV22(ticker);return ((typeof v14!=='undefined'&&Array.isArray(v14.history))?v14.history:[]).filter(t=>tickerV22(t.ticker)===key&&(+t.qty||0)>0&&isoDateV22(t.date));}
function qtyAtDateV22(h,date){const current=Math.max(0,+h.qty||0),d=isoDateV22(date);if(!d)return {qty:current,estimated:true};let q=current;const later=historyForTickerV22(h.ticker).filter(t=>t.date>d);later.forEach(t=>{const n=Math.max(0,+t.qty||0);if(t.side==='Compra')q-=n;else if(t.side==='Venda')q+=n;});let estimated=false;if(q<0){q=current;estimated=true;}const hist=historyForTickerV22(h.ticker).sort((a,b)=>a.date.localeCompare(b.date));if(!hist.length||d<hist[0].date)estimated=true;return {qty:Math.max(0,q),estimated};}
function eventStatusV22(e){const pay=isoDateV22(e.paymentDate),today=todayV22();if(!pay)return 'Sem data';return pay<=today?'Recebido':'A receber';}
function eventRowsV22(){const holdings=activeHoldingsV22(),by=new Map(holdings.map(h=>[tickerV22(h.ticker),h])),fx=fxV22(),today=todayV22(),out=[];(v22DividendDb.events||[]).forEach(e=>{const key=tickerV22(e.ticker),h=by.get(key);if(!h)return;const ex=isoDateV22(e.exDate),futureEx=ex&&ex>today,qInfo=futureEx?{qty:Math.max(0,+h.qty||0),estimated:false}:qtyAtDateV22(h,ex||e.paymentDate);if(qInfo.qty<=1e-10)return;const amount=Math.max(0,+e.amount||0),currency=String(e.currency||'BRL').toUpperCase(),nativeTotal=amount*qInfo.qty,brlTotal=currency==='USD'?(Number.isFinite(fx)?nativeTotal*fx:null):nativeTotal;out.push({...e,ticker:key,className:h.className||e.className||'',holdingName:h.name||'',qtyEligible:qInfo.qty,estimatedQty:qInfo.estimated,futureEx,nativeTotal,brlTotal,status:eventStatusV22(e)});});return out;}
function currentYearV22(){return String(new Date().getFullYear());}
function dividendMetricsV22(){const rows=eventRowsV22(),year=currentYearV22(),today=todayV22(),receivedYear=rows.filter(r=>r.status==='Recebido'&&String(r.paymentDate||'').startsWith(year)&&Number.isFinite(r.brlTotal)).reduce((s,r)=>s+r.brlTotal,0),upcoming=rows.filter(r=>r.status==='A receber'&&Number.isFinite(r.brlTotal)).reduce((s,r)=>s+r.brlTotal,0);const d12=new Date();d12.setMonth(d12.getMonth()-12);const start=`${d12.getFullYear()}-${String(d12.getMonth()+1).padStart(2,'0')}-${String(d12.getDate()).padStart(2,'0')}`,received12=rows.filter(r=>r.status==='Recebido'&&r.paymentDate>=start&&r.paymentDate<=today&&Number.isFinite(r.brlTotal)).reduce((s,r)=>s+r.brlTotal,0),next=rows.filter(r=>r.status==='A receber'&&isoDateV22(r.paymentDate)).sort((a,b)=>a.paymentDate.localeCompare(b.paymentDate))[0]||null;return {rows,receivedYear,upcoming,received12,next};}
function renderIncomeSummaryV22(){const host=document.getElementById('patrimonyIncomeSummaryV22');if(!host)return;if(!v22DividendLoaded){host.innerHTML='<div class="overviewHeaderV22"><div><h2>Proventos</h2><p>Carregando calendário...</p></div></div><div class="summaryLoadingV22"></div>';return;}const m=dividendMetricsV22();host.innerHTML=`<div class="overviewHeaderV22"><div><h2>Proventos</h2><p>Resumo bruto estimado da carteira atual.</p></div><button type="button" class="ghost compact" data-go-div-v22>Ver proventos</button></div><div class="incomeSummaryGridV22"><div><span>Recebidos em ${currentYearV22()}</span><strong>${moneyV22(m.receivedYear)}</strong></div><div><span>A receber</span><strong>${moneyV22(m.upcoming)}</strong></div><div><span>Recebidos 12 meses</span><strong>${moneyV22(m.received12)}</strong></div><div><span>Próximo pagamento</span><strong>${m.next?brDateV22(m.next.paymentDate):'—'}</strong><small>${m.next?`${escV22(m.next.ticker)} • ${moneyV22(m.next.brlTotal)}`:'Nenhum anunciado'}</small></div></div><div class="incomeNoteV22">Proventos em USD usam o câmbio atual apenas para a visão consolidada em reais.</div>`;host.querySelector('[data-go-div-v22]')?.addEventListener('click',()=>activateTabV22('proventos',true));}
function renderPatrimonySummariesV22(){renderIncomeSummaryV22();renderMicroSummaryV22();}
function keyRangeV22(rows){const dates=rows.map(r=>isoDateV22(r.paymentDate)).filter(Boolean).sort();if(!dates.length)return [];const mode=v22DividendUi.mode,now=new Date();if(mode==='annual'){const ys=[...new Set(dates.map(d=>d.slice(0,4)))].sort();return ys;}if(v22DividendUi.range==='year'){const y=currentYearV22();return Array.from({length:12},(_,i)=>`${y}-${String(i+1).padStart(2,'0')}`);}if(v22DividendUi.range==='all'){const first=dates[0].slice(0,7),last=dates[dates.length-1].slice(0,7);let [y,m]=first.split('-').map(Number),[ey,em]=last.split('-').map(Number),keys=[];while(y<ey||(y===ey&&m<=em)){keys.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m>12){m=1;y++;}if(keys.length>84)break;}return keys;}const n=+v22DividendUi.range||12;const halfFuture=Math.min(6,Math.floor(n/3)),start=new Date(now.getFullYear(),now.getMonth()-(n-halfFuture-1),1);return Array.from({length:n},(_,i)=>monthKeyV22(new Date(start.getFullYear(),start.getMonth()+i,1)));}
function renderDividendChartV22(){const host=document.getElementById('dividendChartV22'),foot=document.getElementById('dividendChartFootV22');if(!host)return;if(!v22DividendLoaded){host.innerHTML='<div class="chartEmptyV22">Carregando proventos...</div>';return;}const rows=eventRowsV22().filter(r=>isoDateV22(r.paymentDate)&&Number.isFinite(r.brlTotal)),keys=keyRangeV22(rows),mode=v22DividendUi.mode,map=new Map(keys.map(k=>[k,{received:0,upcoming:0}]));rows.forEach(r=>{const k=mode==='annual'?r.paymentDate.slice(0,4):r.paymentDate.slice(0,7);if(!map.has(k))return;map.get(k)[r.status==='Recebido'?'received':'upcoming']+=r.brlTotal;});const data=keys.map(k=>({key:k,label:mode==='annual'?k:monthLabelV22(k),...(map.get(k)||{received:0,upcoming:0})}));document.getElementById('divModeMonthlyV22')?.classList.toggle('active',mode==='monthly');document.getElementById('divModeAnnualV22')?.classList.toggle('active',mode==='annual');const range=document.getElementById('divRangeV22');if(range){range.value=v22DividendUi.range;range.disabled=mode==='annual';}if(!data.length){host.innerHTML='<div class="chartEmptyV22">Nenhum provento com data de pagamento disponível.</div>';if(foot)foot.textContent='';return;}const W=1000,H=310,left=72,right=20,top=22,bottom=50,pw=W-left-right,ph=H-top-bottom,max=Math.max(...data.map(d=>d.received+d.upcoming),1)*1.12,slot=pw/data.length,bw=Math.max(12,Math.min(52,slot*.58));let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Proventos recebidos e a receber"><g font-family="Inter,system-ui,sans-serif">`;for(let i=0;i<=4;i++){const val=max*(4-i)/4,y=top+ph*i/4;svg+=`<line x1="${left}" y1="${y}" x2="${W-right}" y2="${y}" stroke="#20344d" stroke-width="1"/><text x="${left-9}" y="${y+4}" text-anchor="end" fill="#7890aa" font-size="10">${escV22(val>=1000?`R$ ${(val/1000).toFixed(1).replace('.',',')}k`:`R$ ${Math.round(val)}`)}</text>`;}data.forEach((d,i)=>{const x=left+slot*i+slot/2,rv=d.received/max*ph,uv=d.upcoming/max*ph,y0=top+ph;svg+=`<rect x="${x-bw/2}" y="${y0-rv}" width="${bw}" height="${rv}" rx="4" fill="#30b77b"><title>${d.label}: recebidos ${moneyV22(d.received)}</title></rect>`;svg+=`<rect x="${x-bw/2}" y="${y0-rv-uv}" width="${bw}" height="${uv}" rx="4" fill="#8ee2bd" opacity=".86"><title>${d.label}: a receber ${moneyV22(d.upcoming)}</title></rect>`;if(data.length<=18||i%Math.ceil(data.length/14)===0)svg+=`<text x="${x}" y="${H-18}" text-anchor="middle" fill="#7890aa" font-size="10" transform="rotate(-35 ${x} ${H-18})">${d.label}</text>`;});svg+='</g></svg>';host.innerHTML=svg;const rec=data.reduce((s,d)=>s+d.received,0),up=data.reduce((s,d)=>s+d.upcoming,0);if(foot)foot.innerHTML=`No período exibido: <strong>${moneyV22(rec)}</strong> recebidos • <strong>${moneyV22(up)}</strong> a receber. Valores são brutos e podem conter estimativas de quantidade/câmbio.`;}
function renderDividendKpisV22(){const host=document.getElementById('dividendKpisV22');if(!host)return;if(!v22DividendLoaded){host.innerHTML='<article class="card dividendKpiV22"><span>Base de proventos</span><strong>Carregando...</strong></article>';return;}const m=dividendMetricsV22();host.innerHTML=`<article class="card dividendKpiV22"><span>Recebidos em ${currentYearV22()}</span><strong>${moneyV22(m.receivedYear)}</strong><small>estimativa bruta</small></article><article class="card dividendKpiV22"><span>A receber</span><strong>${moneyV22(m.upcoming)}</strong><small>pagamentos já mapeados</small></article><article class="card dividendKpiV22"><span>Recebidos 12 meses</span><strong>${moneyV22(m.received12)}</strong><small>carteira atual</small></article><article class="card dividendKpiV22"><span>Próximo pagamento</span><strong>${m.next?brDateV22(m.next.paymentDate):'—'}</strong><small>${m.next?`${escV22(m.next.ticker)} • ${moneyV22(m.next.brlTotal)}`:'nenhum evento futuro'}</small></article>`;}
function formatUnitDividendV22(r){const cur=String(r.currency||'BRL').toUpperCase(),v=+r.amount||0;return cur==='USD'?`US$ ${v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:6})}`:`R$ ${v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:6})}`;}
function renderDividendTableV22(){const body=document.getElementById('dividendRowsV22'),cov=document.getElementById('dividendCoverageV22');if(!body)return;const sel=document.getElementById('divStatusV22');if(sel)sel.value=v22DividendUi.status;if(!v22DividendLoaded){body.innerHTML='<tr><td colspan="9"><div class="emptyState">Carregando calendário de proventos...</div></td></tr>';return;}let rows=eventRowsV22();if(v22DividendUi.status==='Recebidos')rows=rows.filter(r=>r.status==='Recebido');if(v22DividendUi.status==='A receber')rows=rows.filter(r=>r.status==='A receber');rows.sort((a,b)=>{if(a.status!==b.status)return a.status==='A receber'?-1:1;if(a.status==='A receber')return String(a.paymentDate||'9999').localeCompare(String(b.paymentDate||'9999'));return String(b.paymentDate||'').localeCompare(String(a.paymentDate||''));});body.innerHTML=rows.length?rows.map(r=>`<tr><td><div class="divAssetV22"><strong>${escV22(r.ticker)}</strong><small>${escV22(r.holdingName||'')}</small></div></td><td><span class="classBadge">${escV22(r.className||'—')}</span></td><td>${escV22(r.type||'Provento')}</td><td>${brDateV22(r.exDate)}${r.futureEx?'<small class="futureComV22"> futura</small>':''}</td><td>${brDateV22(r.paymentDate)}</td><td>${formatUnitDividendV22(r)}</td><td>${(+r.qtyEligible||0).toLocaleString('pt-BR',{maximumFractionDigits:6})}${r.estimatedQty?'<small class="estimatedV22"> estim.</small>':''}</td><td><strong>${Number.isFinite(r.brlTotal)?moneyV22(r.brlTotal):'—'}</strong>${String(r.currency||'BRL').toUpperCase()==='USD'?'<small class="estimatedV22"> câmbio atual</small>':''}</td><td><span class="dividendStatusV22 ${r.status==='Recebido'?'received':'upcoming'}">${escV22(r.status)}</span></td></tr>`).join(''):'<tr><td colspan="9"><div class="emptyState">Nenhum provento encontrado para este filtro.</div></td></tr>';if(cov){const active=activeHoldingsV22().map(h=>tickerV22(h.ticker)),covered=new Set((v22DividendDb.events||[]).map(e=>tickerV22(e.ticker))),missing=active.filter(t=>!covered.has(t));const upd=v22DividendDb.updatedAt?new Date(v22DividendDb.updatedAt).toLocaleString('pt-BR'):'—';cov.innerHTML=`<span>Base atualizada: <strong>${escV22(upd)}</strong></span><span>${covered.size} ativo(s) com eventos na base</span>${missing.length?`<span class="coverageWarnV22">Sem eventos automáticos na base para: ${escV22(missing.join(', '))}</span>`:''}`;}}
function renderDividendsV22(){renderDividendKpisV22();renderDividendChartV22();renderDividendTableV22();renderIncomeSummaryV22();}
async function loadDividendsV22(){try{const r=await fetch(`dividends.json?v=${Date.now()}`,{cache:'no-store'});if(r.ok){const j=await r.json();v22DividendDb={updatedAt:j.updatedAt||null,events:Array.isArray(j.events)?j.events:[],sources:Array.isArray(j.sources)?j.sources:[]};}}catch(e){console.warn('[V2.2] falha ao carregar proventos',e);}v22DividendLoaded=true;renderDividendsV22();}
function afterRenderV22(){if(!v22Ready)return;ensureTabLayoutV22();updateVersionV22();renderPatrimonySummariesV22();if(v22ActiveTab==='proventos')renderDividendsV22();activateTabV22(v22ActiveTab,false);}
function initV22(){if(v22Ready)return;v22Ready=true;ensureCssV22();ensureTabLayoutV22();const previousRender=render;render=function(){const result=previousRender();afterRenderV22();return result;};updateVersionV22();activateTabV22(v22ActiveTab,false);renderPatrimonySummariesV22();loadDividendsV22();window.addEventListener('hashchange',()=>{const t=String(location.hash||'').replace('#','');if(V22_TABS.includes(t))activateTabV22(t,false);});}
let attempts=0;const boot=()=>{attempts++;if(typeof state==='undefined'||typeof render!=='function'||typeof renderPatrimonyEvolutionV15!=='function'||typeof postRenderV20!=='function'||!document.querySelector('.holdingsCard')||!document.getElementById('transactionsSection')){if(attempts<400)setTimeout(boot,25);return;}initV22();};boot();
})();
