(()=>{
const V23_TAB_KEY='carteira-v23-tab';
const V23_TABS=['patrimonio','alocacao','aportes','proventos'];
const V23_LABELS={patrimonio:'Patrimônio',alocacao:'Alocação estruturada',aportes:'Aportes & lançamentos',proventos:'Proventos'};
const V23_ICONS={patrimonio:'◫',alocacao:'◎',aportes:'↗',proventos:'◌'};
const V23_PANEL={patrimonio:'tabPatrimonioV22',alocacao:'tabMacroV22',aportes:'tabMicroV22',proventos:'tabProventosV22'};
let v23Ready=false;
let v23ActiveTab=(()=>{const raw=String(location.hash||'').replace('#','');const migrated=raw==='macro'?'alocacao':raw==='micro'?'aportes':raw;if(V23_TABS.includes(migrated))return migrated;const saved=localStorage.getItem(V23_TAB_KEY);return V23_TABS.includes(saved)?saved:'patrimonio';})();
function escV23(v){return typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function moneyV23(v){return typeof fmt!=='undefined'&&fmt?.format?fmt.format(+v||0):`R$ ${(+v||0).toFixed(2)}`;}
function pctV23(v){return typeof pct==='function'?pct(+v||0):`${(+v||0).toFixed(1).replace('.',',')}%`;}
function ensureCssV23(){if(document.querySelector('link[href^="v23.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='v23.css?v=23.0';document.head.appendChild(l);}
function updateVersionV23(){const e=document.querySelector('.topbar .eyebrow');if(e)e.textContent='CARTEIRA • V2.3';const p=document.querySelector('.topbar p');if(p)p.textContent='Acompanhe patrimônio e proventos, visualize sua alocação e concentre o planejamento operacional de aportes e lançamentos em uma área dedicada.';}
function rebuildNavV23(){const nav=document.getElementById('portfolioTabsV22');if(!nav)return;nav.classList.add('portfolioTabsV23');nav.setAttribute('aria-label','Seções da carteira');nav.innerHTML=V23_TABS.map(t=>`<button type="button" data-tab-v23="${t}"><span class="tabIconV22">${V23_ICONS[t]}</span><span>${V23_LABELS[t]}</span></button>`).join('');nav.querySelectorAll('[data-tab-v23]').forEach(b=>b.onclick=()=>activateTabV23(b.dataset.tabV23,true));}
function setIntroV23(panelId,eyebrow,title,text){const panel=document.getElementById(panelId);if(!panel)return;let intro=panel.querySelector('.tabIntroV22');if(!intro){intro=document.createElement('div');intro.className='tabIntroV22';panel.insertAdjacentElement('afterbegin',intro);}intro.innerHTML=`<div><span class="tabEyebrowV22">${eyebrow}</span><h2>${title}</h2><p>${text}</p></div>`;}
function ensureAllocationMacroTableV23(){const panel=document.getElementById('tabMacroV22');if(!panel)return null;let card=document.getElementById('allocationMacroSnapshotV23');if(!card){card=document.createElement('section');card.id='allocationMacroSnapshotV23';card.className='card allocationMacroSnapshotV23';card.innerHTML='<div class="sectionTitle"><div><h2>Estrutura macro atual</h2><p>Visão somente leitura da distribuição consolidada por classe, comparada aos seus alvos e à banda vigente.</p></div><span id="allocationTargetTotalV23" class="pill"></span></div><div id="allocationMacroRowsV23" class="allocationMacroRowsV23"></div>';const intro=panel.querySelector('.tabIntroV22');intro?.insertAdjacentElement('afterend',card);}return card;}
function renderAllocationMacroV23(){const host=document.getElementById('allocationMacroRowsV23');if(!host||typeof state==='undefined')return;const rows=typeof getRows==='function'?getRows():[];const targetTotal=rows.reduce((s,r)=>s+(+r.target||0),0);const pill=document.getElementById('allocationTargetTotalV23');if(pill){pill.textContent=`Metas ${pctV23(targetTotal)}`;pill.classList.toggle('warn',Math.abs(targetTotal-100)>.05);}host.innerHTML=rows.length?rows.map((r,i)=>{const status=r.balanced?'Na banda':(r.currentWeight<r.min?'Abaixo':'Acima');const cls=r.balanced?'good':(r.currentWeight<r.min?'warn':'bad');const width=Math.min(100,Math.max(0,r.currentWeight));const targetPos=Math.min(100,Math.max(0,r.target));return `<article class="allocationMacroRowV23 ${cls}"><div class="allocationMacroNameV23"><i style="background:${typeof colorForIndex==='function'?colorForIndex(i):'#69a7ff'}"></i><div><strong>${escV23(r.name)}</strong><small>${moneyV23(r.current)}</small></div></div><div class="allocationMacroNumbersV23"><span><small>Atual</small><strong>${pctV23(r.currentWeight)}</strong></span><span><small>Alvo</small><strong>${pctV23(r.target)}</strong></span><span><small>Faixa</small><strong>${pctV23(r.min)} – ${pctV23(r.max)}</strong></span><span><small>Status</small><strong>${status}</strong></span></div><div class="allocationTrackV23"><i style="width:${width}%"></i><b style="left:${targetPos}%" title="Alvo ${pctV23(r.target)}"></b></div></article>`;}).join(''):'<div class="emptyState">Nenhuma classe cadastrada.</div>';}
function fixPatrimonyOverviewV23(){const grid=document.getElementById('patrimonyOverviewGridV22');if(grid)grid.classList.add('patrimonyOverviewSingleV23');const income=document.getElementById('patrimonyIncomeSummaryV22');if(income&&grid&&income.parentElement!==grid)grid.appendChild(income);const btn=income?.querySelector('[data-go-div-v22]');if(btn){const clone=btn.cloneNode(true);clone.textContent='Ver proventos';clone.onclick=()=>activateTabV23('proventos',true);btn.replaceWith(clone);}}
function configureAllocationContentV23(){const panel=document.getElementById('tabMacroV22');if(!panel)return;setIntroV23('tabMacroV22','VISÃO DA CARTEIRA','Alocação estruturada','Concentre aqui a estrutura atual da carteira: macro alocação por classe e micro alocação por ativos e segmentos.');const macroCard=ensureAllocationMacroTableV23();const charts=document.querySelector('.chartsCard');if(charts){if(charts.parentElement!==panel)panel.appendChild(charts);const h=charts.querySelector('.sectionTitle h2');if(h)h.innerHTML='Macro alocação atual';const p=charts.querySelector('.sectionTitle p');if(p)p.textContent='Compare visualmente os pesos atuais das classes com os pesos-alvo definidos.';if(macroCard&&charts.previousElementSibling!==macroCard)macroCard.insertAdjacentElement('afterend',charts);}const microSummary=document.getElementById('patrimonyMicroSummaryV22');if(microSummary){microSummary.classList.add('allocationMicroSummaryV23');if(microSummary.parentElement!==panel)panel.appendChild(microSummary);const h=microSummary.querySelector('.overviewHeaderV22 h2');if(h)h.textContent='Resumo gráfico da micro alocação';const p=microSummary.querySelector('.overviewHeaderV22 p');if(p)p.textContent='Distribuição setorial atual dentro de cada classe, comparada aos alvos já definidos.';microSummary.querySelector('[data-go-micro-v22]')?.remove();}const holdings=document.querySelector('.holdingsCard');if(holdings){holdings.classList.add('allocationHoldingsV23');if(holdings.parentElement!==panel)panel.appendChild(holdings);const title=holdings.querySelector('.holdingsTitleV18 h2,.sectionTitle h2');if(title)title.textContent='Micro alocação detalhada';const sub=holdings.querySelector('.holdingsTitleV18 p,.sectionTitle p');if(sub)sub.textContent='Ativos, preços, variação e distribuição por segmento de cada classe da carteira.';}renderAllocationMacroV23();}
function configureContributionsContentV23(){const panel=document.getElementById('tabMicroV22');if(!panel)return;setIntroV23('tabMicroV22','PLANEJAMENTO E EXECUÇÃO','Aportes & lançamentos','Planeje o aporte, teste o impacto macro e micro, simule operações e execute os lançamentos quando estiver satisfeito.');const budget=document.getElementById('macroBudgetCardV22');if(budget){if(budget.parentElement!==panel)panel.appendChild(budget);const h=budget.querySelector('.sectionTitle h2');if(h)h.textContent='Planejamento de aportes';const p=budget.querySelector('.sectionTitle p');if(p)p.textContent='Defina o orçamento mensal e use a sugestão automática como ponto de partida antes de testar os lançamentos.';}const layout=document.querySelector('.layout');if(layout&&layout.parentElement!==panel)panel.appendChild(layout);const tx=document.getElementById('transactionsSection');if(tx&&tx.parentElement!==panel)panel.appendChild(tx);const recommendation=document.querySelector('.recommendation .sectionTitle h2');if(recommendation)recommendation.childNodes[0].nodeValue='Distribuição planejada ';const txTitle=tx?.querySelector('.sectionTitle h2');if(txTitle)txTitle.childNodes[0].nodeValue='Lançamentos & simulação de aportes ';}
function configurePatrimonyV23(){const panel=document.getElementById('tabPatrimonioV22');if(!panel)return;const kpis=document.getElementById('kpis'),evo=document.querySelector('.evolutionCard');if(kpis&&kpis.parentElement!==panel)panel.appendChild(kpis);if(evo&&evo.parentElement!==panel)panel.appendChild(evo);fixPatrimonyOverviewV23();}
function ensureLayoutV23(){rebuildNavV23();configurePatrimonyV23();configureAllocationContentV23();configureContributionsContentV23();setIntroV23('tabProventosV22','RENDA DA CARTEIRA','Proventos','Acompanhe pagamentos recebidos e anunciados somente para posições que fazem parte da sua carteira.');updateVersionV23();}
function activateTabV23(tab,pushHash=false){if(!V23_TABS.includes(tab))tab='patrimonio';v23ActiveTab=tab;localStorage.setItem(V23_TAB_KEY,tab);if(pushHash&&location.hash!==`#${tab}`)history.replaceState(null,'',`#${tab}`);document.querySelectorAll('.tabPanelV22').forEach(p=>p.classList.toggle('hiddenV22',p.id!==V23_PANEL[tab]));document.querySelectorAll('[data-tab-v23]').forEach(b=>{const active=b.dataset.tabV23===tab;b.classList.toggle('active',active);b.setAttribute('aria-selected',active?'true':'false');});if(tab==='patrimonio'){try{if(typeof renderPatrimonyEvolutionV15==='function')renderPatrimonyEvolutionV15();}catch(e){}try{if(typeof renderIncomeSummaryV22==='function')renderIncomeSummaryV22();}catch(e){}}if(tab==='alocacao')renderAllocationMacroV23();if(tab==='proventos'){try{if(typeof renderDividendsV22==='function')renderDividendsV22();}catch(e){}}}
function afterRenderV23(){if(!v23Ready)return;ensureLayoutV23();activateTabV23(v23ActiveTab,false);}
function initV23(){if(v23Ready)return;v23Ready=true;ensureCssV23();ensureLayoutV23();const previousRender=render;render=function(){const result=previousRender();afterRenderV23();return result;};activateTabV23(v23ActiveTab,false);window.addEventListener('hashchange',()=>{const raw=String(location.hash||'').replace('#','');const tab=raw==='macro'?'alocacao':raw==='micro'?'aportes':raw;if(V23_TABS.includes(tab))activateTabV23(tab,false);});}
let attempts=0;const boot=()=>{attempts++;if(typeof render!=='function'||!document.getElementById('portfolioTabsV22')||!document.getElementById('tabMacroV22')||!document.getElementById('tabMicroV22')){if(attempts<400)setTimeout(boot,25);return;}initV23();};boot();
})();
